import * as fs from 'fs';
import * as path from 'path';
import { Command } from 'commander';
import {
  registerAllRules,
  Analyzer,
  loadConfig,
  loadBaseline,
  filterAgainstBaseline,
  summarize,
  groupByFile,
  IgnoreMatcher
} from '@ied/core';
import type { Diagnostic, ResolvedConfig } from '@ied/core';
import { collectFiles } from './collect';

/** Cap on how many findings to list per file before collapsing the remainder. */
const MAX_PER_FILE = 25;

interface CiCommentOptions {
  format: string;
  baseline?: string;
  dryRun?: boolean;
}

function loc(d: Diagnostic): string {
  return `${d.range.start.row + 1}:${d.range.start.column + 1}`;
}

/** Render the findings as a GitHub-flavoured Markdown comment. */
function renderMarkdown(diags: Diagnostic[]): string {
  const s = summarize(diags);
  const lines: string[] = [];
  lines.push('## 🔍 Invisible Errors Detector');
  lines.push('');
  if (diags.length === 0) {
    lines.push('✅ No new findings introduced in this change.');
    return lines.join('\n');
  }
  lines.push(
    `Found **${s.total}** new finding${s.total === 1 ? '' : 's'}: ` +
      `❌ ${s.error} error${s.error === 1 ? '' : 's'}, ` +
      `⚠️ ${s.warning} warning${s.warning === 1 ? '' : 's'}, ` +
      `ℹ️ ${s.info} info across ${s.files} file${s.files === 1 ? '' : 's'}.`
  );
  lines.push('');

  const byFile = groupByFile(diags);
  for (const [file, list] of byFile) {
    lines.push(`<details><summary><b>${file}</b> — ${list.length} finding${list.length === 1 ? '' : 's'}</summary>`);
    lines.push('');
    lines.push('| Line | Severity | Rule | Message |');
    lines.push('| --- | --- | --- | --- |');
    const shown = list.slice(0, MAX_PER_FILE);
    for (const d of shown) {
      lines.push(`| ${loc(d)} | ${d.severity} | \`${d.ruleId}\` | ${d.message.replace(/\|/g, '\\|')} |`);
    }
    if (list.length > shown.length) {
      lines.push('');
      lines.push(`_…and ${list.length - shown.length} more in this file._`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }
  lines.push('<sub>Generated by `ied ci-comment`. Findings already in the baseline are not shown.</sub>');
  return lines.join('\n');
}

/** Resolve the PR number from GitHub Actions env (ref or event payload). */
function resolvePrNumber(): number | null {
  const ref = process.env.GITHUB_REF ?? '';
  const m = ref.match(/refs\/pull\/(\d+)\//);
  if (m) return Number(m[1]);
  const eventPath = process.env.GITHUB_EVENT_PATH;
  if (eventPath && fs.existsSync(eventPath)) {
    try {
      const evt = JSON.parse(fs.readFileSync(eventPath, 'utf8'));
      const n = evt?.pull_request?.number ?? evt?.number;
      if (typeof n === 'number') return n;
    } catch {
      /* ignore malformed event payload */
    }
  }
  return null;
}

async function postGitHubComment(markdown: string): Promise<boolean> {
  const token = process.env.GITHUB_TOKEN;
  const repo = process.env.GITHUB_REPOSITORY; // "owner/repo"
  const pr = resolvePrNumber();
  if (!token || !repo || pr === null) {
    return false;
  }
  const [owner, name] = repo.split('/');
  const url = `https://api.github.com/repos/${owner}/${name}/issues/${pr}/comments`;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'User-Agent': 'ied-ci',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({ body: markdown })
  });
  if (!res.ok) {
    const text = await res.text().catch(() => '');
    throw new Error(`GitHub API responded ${res.status}: ${text.slice(0, 300)}`);
  }
  return true;
}

export function ciCommentCommand(): Command {
  const cmd = new Command('ci-comment');
  cmd
    .description('Analyze, then post newly-introduced findings as a PR comment (GitHub).')
    .argument('[paths...]', 'files or directories to scan', ['.'])
    .option('-f, --format <format>', 'comment format: github', 'github')
    .option('--baseline [file]', 'baseline file to diff against (default .ied-baseline.json if present)')
    .option('--dry-run', 'print the comment markdown instead of posting it')
    .action(async (paths: string[], opts: CiCommentOptions) => {
      if (opts.format !== 'github') {
        console.error(`Unsupported --format "${opts.format}" (only "github" is supported).`);
        process.exit(2);
        return;
      }

      registerAllRules();
      const rootDir = process.cwd();
      let config: ResolvedConfig;
      try {
        config = loadConfig(rootDir);
      } catch (err) {
        console.error(err instanceof Error ? err.message : String(err));
        process.exit(2);
        return;
      }

      const ignore = IgnoreMatcher.fromFiles(rootDir);
      const files = collectFiles(paths, config, ignore, rootDir);

      const analyzer = new Analyzer(config);
      let all: Diagnostic[] = [];
      try {
        for (const file of files) {
          const content = fs.readFileSync(file, 'utf8');
          const r = await analyzer.analyzeFile({ filePath: file, content });
          all.push(...r.diagnostics);
        }
      } finally {
        analyzer.dispose();
      }

      // "New" findings = those not present in the baseline (if any).
      const baselinePath =
        typeof opts.baseline === 'string'
          ? opts.baseline
          : config.baseline ?? '.ied-baseline.json';
      const resolvedBaseline = path.resolve(rootDir, baselinePath);
      if (fs.existsSync(resolvedBaseline)) {
        const baseline = loadBaseline(resolvedBaseline);
        if (baseline) all = filterAgainstBaseline(all, baseline);
      }

      const markdown = renderMarkdown(all);
      const summary = summarize(all);

      let posted = false;
      if (!opts.dryRun) {
        try {
          posted = await postGitHubComment(markdown);
        } catch (err) {
          console.error(err instanceof Error ? err.message : String(err));
          process.exit(2);
          return;
        }
      }

      if (!posted) {
        // Dry run, or missing token/PR context — print so it's still useful.
        process.stdout.write(markdown + '\n');
      } else {
        process.stdout.write(`Posted PR comment with ${summary.total} new finding(s).\n`);
      }

      // Gate CI: fail only when NEW error-severity findings were introduced.
      process.exit(summary.error > 0 ? 1 : 0);
    });
  return cmd;
}
